### ISSUE TITLE
[object Object] Gets returned from the reactStringReplace() function

### ISSUE THREAD

**Issue by ismaelbarry** [iansinnott/react-string-replace#50]
```
    const reactStringReplace = require("react-string-replace");
    var array = reactStringReplace("whats your name", "your", (match, i) => (
      <span key={i} style={{ color: "red" }}>
        {match}
      </span>
    ));
```

I'm running the above code (which is from the example) and I get [object Object]. Unfortunately, this is not what the example says I should be getting. What am I doing wrong here?

Currently using React Native v0.61 and react-string-replace@0.4.4

Thanks!

**Comment by erinwilder** [comment]
I'm having the same problem. It returns an array of strings, and the replaced text is an object in the array. I had to wrap the replacement text in string literals to get it to return the right thing and then use join to make it a single string instead of an array. Something seems wrong about it.

**Comment by iansinnott** [comment]
I'm not sure I understand the issue you're having. Perhaps this has something to do with React Native? This is the expected behavior. If you want to replace parts of a string with a react component (rather than another string) the function must return a mixed array of strings and objects. React knows how to render this.

If you want to simply replace strings with other strings, use the built-in`'string'.replace(...)` method instead.

Feel free to reopen if you feel there's still something wrong with the library.

**Comment by jonaspraem** [comment]
why does it return an array of strings, and inserts commas into the strings. It should only inject React Components
